apiVersion: kafka.strimzi.io/v1beta2

kind: KafkaConnect

metadata:

  name: rkedev
  
  annotations:

  # use-connector-resources configures this KafkaConnect

  # to use KafkaConnector resources to avoid

  # needing to call the Connect REST API directly

    strimzi.io/use-connector-resources: "true"

spec:

  version: 2.6.0

  replicas: 1

  bootstrapServers: rkedev-kafka-bootstrap:9092

 # tls:

 #   trustedCertificates:

  #    - secretName: rkedev-cluster-ca-cert

  #      certificate: ca.crt
#tls:
#  authentication:
 #   type: tls
  config:

    group.id: connect-cluster

    offset.storage.topic: connect-cluster-offsets

    config.storage.topic: connect-cluster-configs

    status.storage.topic: connect-cluster-status